export type Grant = {
  id: string;
  status: "pending" | "approved" | "rejected" | string;
  title: string;
  provider_name: string | null;
  provider?: string | null;
  funding_amount_min: number | null;
  funding_amount_max: number | null;
  amount_min?: number | null;
  amount_max?: number | null;
  short_description: string | null;
  description?: string | null;
  sector: string[] | null;
  region: string[] | null;
  eligibility: string[] | null;
  deadline: string | null;
  url?: string | null;
  application_url?: string | null;
  created_at: string;
  source?: string | null;
  contact_email?: string | null;
  additional_notes?: string | null;
  approved_at?: string | null;
  rejection_reason?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
};
